Update to valency in topology files
input-output-hk/cardano-playground pull request #25
Opened 2024-05-14 17:35 UTC by brouwerQ

All the topology examples show a valency of 1, but a lot of SPOs forget to update this value to the number of items in the accessPoints array when adding access points to it (there might be circumstances where you would use another value, but in most cases it'll be equal to the number of access points, not taking into account the case where the domain resolves to multiple ip addresses).

Current JSON is not valid because of the place holder, but I think getting an error message because of this is better than forgetting to change the 1 value.

2024-05-14 17:45 UTC, gufmar requested changes
Please make it a valid JSON that works out of the box.
You could add an additional name/value pair like 

`"valency_explained": "numbers of items in accesspoints"  `

just below the valency name

2024-05-14 17:47 UTC, gufmar commented
For example like here

https://github.com/cardano-community/guild-operators/blob/0597db2fdfc1b8be6db4484dad8a111d6c94873c/files/configs/mainnet/topology.json#L9

2024-05-14 18:16 UTC, brouwerQ commented
@gufmar, like explained it is intentional invalid...

2024-05-15 23:13 UTC, johnalotoski commented
Hi @brouwerQ, thanks for the PR.

Some quick thoughts:
* I agree with @gufmar that json should remain valid in any case
* Creating invalid json that breaks node until it is adjusted in order to bring attention to something that an operator *might* want to change from some initial default value is likely going to create more problems than it solves.
* Keeping valency at 1 and simply adding additional list items is a valid pattern, so for those who do that, there generally isn't a need to adjust valency (unless a multi-ip dns is used), example:
```
{
  "bootstrapPeers": [
    {
      "address": "sanchonet-node.play.dev.cardano.org",
      "port": 3001
    }
  ],
  "localRoots": [
    {
      "accessPoints": [
        {
          "address": "node-a.fqdn",
          "port": 3001
        }
      ],
      "advertise": false,
      "trustable": true,
      "valency": 1
    },
    {
      "accessPoints": [
        {
          "address": "node-b.fqdn",
          "port": 3001
        }
      ],
      "advertise": false,
      "trustable": true,
      "valency": 1
    }
  ],
  "publicRoots": [],
  "useLedgerAfterSlot": 21599922
}
```
* If we either break json or add additional json explainer keys to try to explain things that a consumer *might* be confused about, where do we draw the line?  Certainly there could be confusion about schema usage beyond just the valency.

There is a wiki explaining the p2p schema [here](https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/getting-started/understanding-config-files.md).  Normally I would think it is up to the consumer to understand the schema and adjust their topology accordingly.

To accomplish adding json explainer keys, probably that would be done with a PR from where the config code is generated, in iohk-nix, for example [here](https://github.com/input-output-hk/iohk-nix/blob/master/cardano-lib/default.nix#L41).

2024-05-18 00:20 UTC, johnalotoski commented
> Someone who uses this example needs to edit it anyways, because the file as is with an empty array isn't that useful, so I think this is less of an issue here...

The topologies without localRoots are all valid working edge node topologies which downstream consumers may use directly without further edits.  Yes, SPOs will want to make changes, but breaking the topology file with the intention of helping SPOs will also break it for anyone else who doesn't need localRoots and just wants to run an edge node.

> Yes but there're already multiple cases of an SPO asking for help in the best practices TG group because they see connections from their relay to their BP dropping and in almost every one of those cases the problem was not adjusting the valency to the number of entries.

Ok, I see.  It would be nice to address that.

> A better solution imho would be that the default value for valency would be -1 and if a negative value is used, that it'll be set to the number of entries in the array, so in most cases, you wouldn't need to change it, but that's a more drastic change (although not that drastic, because adding this functionality won't break anything).

That's an interesting idea.

> So all those topology examples are generated with that file?

Mostly yes.  We definitely wouldn't want to make a PR to iohk-nix which would break the topology config there, because those generated configurations get used in automation elsewhere which will end up breaking other things unexpectedly.  Possibly we could PR an explainer key there to get auto-added to all the generated configs, but I'm not really keen on that idea either.  Even if we wanted to merge this PR as it is to playground and not touch iohk-nix, your changes would get overwritten on the next set of updates, so a bit of a different approach would be needed.

I'll aim to update this ticket again sometime next week, possibly late next week, with further feedback/ideas/action.

2024-05-21 14:23 UTC, disassembler commented
We don't want to do this. SPOs should have enough expertise and have read the documentation to run a pool, and should not be dependent on just pulling edge node topology files and copy/pasting roots into it. The security of the network is dependent on the competency of SPOs to know what they're doing and properly craft topology files for their use cases.

2024-05-21 14:23 UTC, closed without merging

2024-05-21 16:26 UTC, brouwerQ commented
@disassembler I understand your reasoning, so I've made an alternative change in the documentation that doesn't touch the examples to clarify the field more: https://github.com/input-output-hk/cardano-node-wiki/pull/48.